// This file was autogenerated by GitRepoData utility
#define GIT_HASH "F1020F9ASFJ089"

#define GIT_VERSION "1.0.0"
#define GIT_VERSION_MAJOR 1
#define GIT_VERSION_MINOR 0
#define GIT_VERSION_PATCH 0
#define GIT_VERSION_TWEAK ".rc-9000"
